'''
CONSTANTS AND CONFIGURATION FILE
Andrea Bertogalli
MoonPatrol 2019
'''
#region ROVERS
ROVER_X = 209
ROVER_Y = 155
ROVER_WIDTH = 33
ROVER_HEIGHT = 24
ROVER_JUMPING_X = 43
ROVER_JUMPING_Y = 100
ROVER_FALLING_X = 78
ROVER_FALLING_Y = 101
ROVER_SPEED = 7
ROVER_TWO_X =  248 
ROVER_TWO_Y = 157
ROVER_TWO_JUMPING_X = 49
ROVER_TWO_JUMPING_Y = 151
ROVER_TWO_FALLING_X = 81
ROVER_TWO_FALLING_Y = 152
#endregion
#region URI
SPRITES_URI = "https://tomamic.github.io/images/sprites/moon-patrol.png"
BACKGROUNDS_URI = "https://tomamic.github.io/images/sprites/moon-patrol-bg.png"
#endregion
#region TERRAIN
TERRAIN_X = 0
TERRAIN_Y = 514
TERRAIN_HEIGHT = 124 
TERRAIN_SPEED = -4
#endregion
#region GREEN_MOUNTAINS
GREEN_MOUNTAIN_X = 0
GREEN_MOUNTAIN_Y = 257
GREEN_MOUNTAIN_HEIGHT = 124
GREEN_MOUNTAINS_SPEED = -2
GREEN_MOUNTAINS_MARGIN_TOP = 180
#endregion
#region BLUE_MOUNTAINS
BLUE_MOUNTAIN_X = 0
BLUE_MOUNTAIN_Y = 0
BLUE_MOUNTAIN_HEIGHT = 254
BLUE_MOUNTAIN_SPEED = - 1
#endregion
#region HOLE
SMALL_HOLE_x = 138
SMALL_HOLE_Y = 140
SMALL_HOLE_WIDTH = 9
SMALL_HOLE_HEIGHT = 13
BIG_HOLE_x = 131
BIG_HOLE_Y = 167
BIG_HOLE_WIDTH = 25
BIG_HOLE_HEIGH = 25
MEDIUM_HOLE_WIDTH = 26
MEDIUM_HOLE_HEIGHT = 21
MEDIUM_HOLE_X = 154
MEDIUM_HOLE_Y = 140
HOLE_SPEED = TERRAIN_SPEED
#endregion
#region EXPLOSIONS
EXPLOSION_X = 164
EXPLOSION_Y = 103
EXPLOSION_WIDTH = 45
EXPLOSION_HEIGHT = 30
BULLET_EXPLOSION_X = 250
BULLET_EXPLOSION_Y = 137
BULLET_EXPLOSION_WIDTH = 15
BULLET_EXPLOSION_HEIGHT = 15
EXPLOSION_TIME = 10
ROCK_EXPLOSION_X = 172
ROCK_EXPLOSION_Y = 287
ROCK_EXPLOSION_WIDTH = 30
ROCK_EXPLOSION_HEIGHT = 31
#endregion
#region ROCK
ROCK_SPEED = TERRAIN_SPEED
SMALL_ROCK_X = 75
SMALL_ROCK_Y = 195
SMALL_ROCK_WIDTH = 20
SMALL_ROCK_HEIGHT = 19
BIG_ROCK_X = 108
BIG_ROCK_Y = 193
BIG_ROCK_WIDTH = 20
BIG_ROCK_HEIGHT = 19
#endregion
#region BULLET
HORIZONTAL = (10, 0)
VERTICAL = (0, 10)
VERTICAL_A = (0, -10)
HORIZONTAL_O = (-10, 0)
BULLET_X = 280
BULLET_Y = 140
BULLET_WIDTH = 15
BULLET_HEIGHT = 15
#endregion
#region SIZES
BIG = 1
MEDIUM = 2
SMALL = 0
#endregion
#region ALIEN
ALIEN_X = 64
ALIEN_Y = 230
ALIEN_WIDTH = 20
ALIEN_HEIGHT = 8
ALIEN_SPEED = 3
ALIEN_MAX_Y = 150
ALIEN_MIN_Y = 50
MAX_ALIEN_NUMBER = 4
ALIEN_POINTS = 2
#endregion
#region TANK
TANK_X = 105
TANK_Y = 242
TANK_WIDTH = 24
TANK_HEIGHT = 20
MAX_TANK_NUMBER = 2
TANK_LIFE = 5
TANK_SPEED = 3
TANK_POINTS = 5
TANK_JUMP_SPEED = 8
#endregion
#region PROBABILITY
OBSTACLE_PROBABILITY = 600
SHOOT_PROBABILITY = 300
ENEMY_PROBABILITY = 600
CHANGE_DIRECTION_PROBABILITY = 100
#endregion
#region OTHER
G = 0.4
BACKGROUND_WIDTH = 509
PLAYER_ONE = 1
PLAYER_TWO = 2
RIGHT = 0
LEFT = 1
UP = 2
DOWN = 3
STAY = 4
#endregion













